version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: 'redis:latest'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  jobs:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'webservice'
    build: .
    command: bash start_jobs
    volumes:
      - '.:/films-api'
    volumes_from:
      - box

  webservice:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash start
    ports:
      - '3000:3000'
    volumes:
      - '.:/films-api'
    volumes_from:
      - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  redis:
  postgres:
  box: